
# /Users/tal/Dropbox/Code/neurosynth/neurosynth/base/parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '3CFA3369D62E748D41C546F02C0CB00D'
    
_lr_action_items = {'LPAR':([0,1,9,10,11,],[1,1,1,1,1,]),'AND':([2,3,4,5,6,7,13,14,15,16,17,18,19,],[-9,-8,11,11,-6,-7,-10,-11,-5,11,11,11,-4,]),'OR':([2,3,4,5,6,7,13,14,15,16,17,18,19,],[-9,-8,9,9,-6,-7,-10,-11,-5,9,9,9,-4,]),'ANDNOT':([2,3,4,5,6,7,13,14,15,16,17,18,19,],[-9,-8,10,10,-6,-7,-10,-11,-5,10,10,10,-4,]),'WORD':([0,1,2,3,6,7,9,10,11,],[2,2,6,7,-6,-7,2,2,2,]),'FLOAT':([8,12,],[14,14,]),'RT':([2,3,4,5,6,7,13,14,15,16,17,18,19,],[-9,-8,8,8,-6,-7,-10,-11,-5,8,8,8,-4,]),'$end':([2,3,4,6,7,13,14,15,16,17,18,19,],[-9,-8,0,-6,-7,-10,-11,-5,-3,-1,-2,-4,]),'LT':([2,3,4,5,6,7,13,14,15,16,17,18,19,],[-9,-8,12,12,-6,-7,-10,-11,-5,12,12,12,-4,]),'RPAR':([2,3,5,6,7,13,14,15,16,17,18,19,],[-9,-8,13,-6,-7,-10,-11,-5,-3,-1,-2,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'feature':([0,1,9,10,11,],[3,3,3,3,3,]),'freq':([8,12,],[15,19,]),'list':([0,1,9,10,11,],[4,5,16,17,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> list","S'",1,None,None,None),
  ('list -> list ANDNOT list','list',3,'p_list_andnot','lexparser.py',67),
  ('list -> list AND list','list',3,'p_list_and','lexparser.py',71),
  ('list -> list OR list','list',3,'p_list_or','lexparser.py',76),
  ('list -> list LT freq','list',3,'p_list_lt','lexparser.py',81),
  ('list -> list RT freq','list',3,'p_list_rt','lexparser.py',85),
  ('feature -> WORD WORD','feature',2,'p_feature_words','lexparser.py',89),
  ('feature -> feature WORD','feature',2,'p_feature_words','lexparser.py',90),
  ('list -> feature','list',1,'p_list_feature','lexparser.py',94),
  ('list -> WORD','list',1,'p_list_feature','lexparser.py',95),
  ('list -> LPAR list RPAR','list',3,'p_list_expr','lexparser.py',101),
  ('freq -> FLOAT','freq',1,'p_freq_float','lexparser.py',105),
]
